log_dir: "Models/JVS_hear"
save_freq: 30
device: "cuda"
epochs: 150
batch_size: 5
pretrained_model: ""
load_only_params: false
fp16_run: true

train_data: "Data/train_list.txt"
val_data: "Data/val_list.txt"

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00100.pth"
GEN_path: "Models/JVS100_integration"

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

loss_params:
  lambda_rec: 1.
  lambda_norm: 1.
  lambda_asr: 10.
  lambda_f0: 5.
  lambda_f0_sty: 0.1
  norm_bias: 0.5
  
optimizer_params:
  lr: 0.0001
